apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummydashboard-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fajrikornel/argocd-demo.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: dummydashboard
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
